# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  displayName: Sonar Prepare Analysis
  inputs:
    SonarCloud: 'sonarcloud-jpw'
    organization: '2102-feb08-net'
    scannerMode: 'MSBuild'
    projectKey: '2102-feb08-net_johnw-project1'
    projectName: 'BookStore'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: dotnet build
  workingDirectory: 'BookStore'

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration) --collect "xplat code coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura,opencover'
    workingDirectory: 'BookStore'

- task: SonarCloudAnalyze@1
  displayName: Sonar Run Analysis

- task: SonarCloudPublish@1
  displayName: Sonar Publish Quality Gate
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'BookStore/BookStore.Web'
    zipAfterPublish: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(d451f1cb-20dd-4a94-8f6a-fae5e3a63a1b)'
    appType: 'webApp'
    WebAppName: 'johnw-project1'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
