# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build BookStore/ --configuration $(buildConfiguration)
  displayName: 'Build'

- script: dotnet test BookStore/BookStore.Tests/
  displayName: 'Unit Testing'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'BookStore/BookStore.Web'
    zipAfterPublish: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(d451f1cb-20dd-4a94-8f6a-fae5e3a63a1b)'
    appType: 'webApp'
    WebAppName: 'johnw-project1'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
